.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. smartcash_qt test_smartcash_qt
clean: FORCE
	$(MAKE) -C .. smartcash_qt_clean test_smartcash_qt_clean
check: FORCE
	$(MAKE) -C .. test_smartcash_qt_check
smartcash-qt smartcash-qt.exe: FORCE
	 $(MAKE) -C .. smartcash_qt
